### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by lammermann** [Rust-Ninja-Sabi/rust-egui-seven-tasks#1]
Hello, thanks for this repo. 

I would like to do the other 2 tasks and use this repo as a starting point. To do this legally, however, there needs to be a lisence to this code.
Would you consider adding a license?

Greetings, Benjamin

**Comment by Rust-Ninja-Sabi** [comment]
Hi Benjamin,

I published the MIT license. It would be great if you would accomplish this repo.

Best regards Sabi

**Comment by lammermann** [comment]
Thank you very much
